language: android
jdk: oraclejdk8

cache:
 directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-27
    - sys-img-armeabi-v7a-android-27
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-26"
  - yes | sdkmanager "platforms;android-27"

before_script:
  - touch local.properties

script:
  - "./gradlew clean build"